In [2]:
import numpy as np
display(np.__version__)
# https://code.tutsplus.com/pt/tutorials/introducing-numpy--cms-28703

'1.19.1'

In [25]:
# criando um array
my_array = np.array(((6,12,93,2),
                     (5,26,78,90),
                     (3,12,16,22),
                     (5,3,1,16)))
display(my_array)
# tipo dos dados
display(my_array.dtype)
# dimensões da matriz 
display(my_array.shape)
# números de elementos da matriz
display(my_array.size)
# tamanho de cada elemento da matriz
display(my_array.itemsize)
# número de dimensões 
display(my_array.ndim)
#criando um matriz com uma linha e cinco colunas
my_array = np.array((1,2,3,4,5))
display(my_array)
#criando um tipo de dados
height_type = np.dtype([('height',np.float)])
display(height_type)
# criando uma matriz com um tipo específico 
my_array = np.array([(1.78,),(1.69,),(1.88,)],dtype=height_type)
display(my_array)
# selecionando um elemento da matriz 
display(my_array[0])

# criando matrizes vazias
# numpy.empty(shape,dtype,order)
empty_array = np.empty([2,2],dtype=int)
display(empty_array)

#criando um matriz de zeros
zeros_array = np.zeros([2,2],dtype=int)
display(zeros_array)

# matrizes com valores uniformemente distribuídos
# numpy.arrange(start, strop, step, dtype)
my_array = np.arange(0,10)
display(my_array)

array([[ 6, 12, 93,  2],
       [ 5, 26, 78, 90],
       [ 3, 12, 16, 22],
       [ 5,  3,  1, 16]])

dtype('int64')

(4, 4)

16

8

2

array([1, 2, 3, 4, 5])

dtype([('height', '<f8')])

array([(1.78,), (1.69,), (1.88,)], dtype=[('height', '<f8')])

(1.78,)

array([[0, 0],
       [0, 0]])

array([[0, 0],
       [0, 0]])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# remodelando uma matriz
my_array = np.arange(0,16)
display(my_array)
my_array = np.reshape(my_array,(4,4))
display(my_array)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
array_1 = np.reshape(np.arange(1,26),(5,5))
display(array_1)
array_2 = np.reshape(np.arange(26,1,-1),(5,5))
display(array_2)
np.concatenate((array_2,array_1),axis=1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[26, 25, 24, 23, 22],
       [21, 20, 19, 18, 17],
       [16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2]])

array([[26, 25, 24, 23, 22,  1,  2,  3,  4,  5],
       [21, 20, 19, 18, 17,  6,  7,  8,  9, 10],
       [16, 15, 14, 13, 12, 11, 12, 13, 14, 15],
       [11, 10,  9,  8,  7, 16, 17, 18, 19, 20],
       [ 6,  5,  4,  3,  2, 21, 22, 23, 24, 25]])